### PR TITLE
feat: Add afterwares which runs after a request is made (after middlewares)

### PR DESCRIPTION
**Pull request by drager**
This pull request adds `afterwares` which runs after a request is made (after middlewares). It fixes issue #284.

Afterwares runs after a request is made and after a middleware. It will return you the whole response, so you can handle status codes and errors properly. It will for example ease the use of checking if user is authenticated, i.e. check if the request did return an 401 response.

It can be used similar to how a `middleware` is used, it is the second parameter to the `use` function.

Maybe we should break out the `use` function to two functions instead. One called for instance `useMiddlewares` which will take your middlewares and another called `useAfterwares` which will simply take your afterwares. I didn't do this change because I didn't want to break the API.

Let me know what you think, thanks!

### CODE REVIEW

**Comment by stubailo** [comment]
Hey, this is really cool - I might not have a chance to get to it today. A few comments:

1. I think it's not a good idea to have the `use` function take two arrays, that could result in some pretty hard to read code. Perhaps we can add another method like `useAfter` or something.
2. I'm not convinced that using the HTTP code on the GraphQL response is a good idea, but I guess at the end of the day you should do that if you want to.

**Comment by drager** [comment]
@stubailo: 
1. Yeah, I thought so too regarding `use`. Will add another `useAfter` function.
2. Why isn't that a good idea would you say?

**Comment by stubailo** [comment]
I guess to me it seems like HTTP codes and similar are an HTTP/REST thing, and I'd prefer to keep my GraphQL server to just queries and responses without worrying about transport-specific stuff like codes. But it's just a preference - I don't have a real justification for it.

In my app, I've implemented login as a totally out-of-band thing that doesn't use GraphQL at all.

**Comment by drager** [comment]
Ah I see. Yeah, that makes sense. I also have the login implemented outside of graphql but to make requests to my graphql endpoint I need users to be authenticated and since I use JWT for authentication and a user could easily "fake" a JWT I need to "throw" people out of the client application if the server returns an authentication error.

**Comment by stubailo** [comment]
> I need to "throw" people out of the client application if the server returns an authentication error.

I guess this can be useful to handle generic application-level errors! So in my world I would probably put that as a GraphQL error rather than an HTTP code, but it could use the same functionality you are building here.

**Comment by drager** [comment]
Yeah, I agree. It could probably be handled by returning a GraphQL error.

**Comment by drager** [comment]
The code is updated to provide a new function called `useAfter()`. Let me know what you think @stubailo.

**Comment by stubailo** [comment]
Looks pretty good to me!

**Comment by stubailo** [comment]
Can you rebase/merge master, and resolve the conflicts? Then I can merge it right away.

**Comment by drager** [comment]
@stubailo: Great, it's now updated.

**Comment by stubailo** [comment]
@drager can you add some docs about this feature? https://github.com/apollostack/docs/blob/master/source/apollo-client/network.md

**Comment by drager** [comment]
@stubailo: Yeah, I'm already on it.

**Pull request merged**
