### PR TITLE
Use typescript/libs instead of es6-shim

### PR DESCRIPTION
**Pull request by kamilkisiela**
@helfer @tmeasday Works with `typedoc` but you should check it, just to be sure

### CODE REVIEW

**Comment by kamilkisiela** [comment]
I could disable this email notification thing in Travis, it's annoying...

**Comment by helfer** [comment]
Thanks @kamilkisiela! @tmeasday can you test if it works with typedoc?

**Comment by kamilkisiela** [comment]
I also moved `npm prune` before `npm install` in travis and appveyor so we have always clean `node_modules`. If this PR won't pass I'll create new one with just this change.

**Comment by tmeasday** [comment]
Thank you for doing this properly @kamilkisiela :). WFM.

Still don't understand what `types: ['es6']` does, btw ;)

**Comment by kamilkisiela** [comment]
I think that `compilerOptions.lib` just adds files with types declarations. Somehow `typedoc` doesn't support this option so I just made TS compiler to not include lib files and I put them manually.

**Comment by helfer** [comment]
Wonderful, thanks!

**Pull request merged**
