### PR TITLE
Pass query variables to reducer function

### PR DESCRIPTION
**Pull request by Siyfion**
References issue #939.

This allows the reducer to use variables passed to the query in order to determine whether the data is relevant to that query or not.

### CODE REVIEW

**Comment by helfer** [comment]
@Siyfion thanks! Make sure to add a test as well to check that your particular use case is supported. I.e. have two queries with different variables, and make sure the reducer gets called with both sets of variables.

**Comment by helfer** [comment]
@Siyfion if you can add a test today, I can still merge the PR and release a new version with it this week! 🙂 Thanks for your work so far, and let me know if you need any pointers for how to write a test for it!

**Comment by Siyfion** [comment]
Sorry Jonas, I've been off ill the last few days (& today) so I won't get a chance to do any coding until Monday I expect.

**Comment by helfer** [comment]
@Siyfion here's where the tests for result reducers currently live: https://github.com/apollostack/apollo-client/blob/1054d213035cfda674198ee057195ed9d15b54aa/test/mutationResults.ts#L593

I was thinking about some fancy test earlier, but I actually think it's enough if you just start a watchQuery (just like most of the tests there do, but with variables) and then make sure the result reducer gets called with those variables. To do that, you could just add a third query, like [this one](https://github.com/apollostack/apollo-client/blob/1054d213035cfda674198ee057195ed9d15b54aa/test/mutationResults.ts#L619) but with variables.

Let me know if you need help!

**Comment by helfer** [comment]
* bump *

**Pull request merged**
