### PR TITLE
Version 0.7

### PR DESCRIPTION
**Pull request by helfer**
This PR is for version 0.7 of Apollo Client, with the following breaking changes planned. Changes will be made in separate PRs using this branch as the base.

- [x] Remove fragment support
- [ ] Refactor error handling to go through `observer.next` and no longer use `observer.error`
- [x] deep freezing of results in development mode
- [x] ... ?

note: 0.6 was just an update in the graphql typings that this repo uses, so this branch is going to be 0.7

### CODE REVIEW

**Comment by kamilkisiela** [comment]
And #1069 ? :))))

**Comment by intellix** [comment]
And https://github.com/apollostack/apollo-client/pull/1041 :))))

**Comment by makstr** [comment]
what about exposing mockNetworkInterface?

**Comment by helfer** [comment]
@kamilkisiela If you have time to update the PR today, I could merge it into the zero-decimal-six branch!

**Comment by helfer** [comment]
@makstr I think there's a PR by in the works, but it doesn't look like it will be ready in time for 0.6

**Comment by kamilkisiela** [comment]
@helfer Expect it done in couple of hours!

**Comment by helfer** [comment]
@kamilkisiela rollup now prints a bunch of info/warnings to the command line. Is there any way to suppress that?

**Comment by kamilkisiela** [comment]
@helfer Not sure if it's possible but I will try though. 

One thing, since we completely removed `lodash`, I'm going to create another PR to get rid of my work around making `lodash` to work with rollup, mocha etc. So wait for it before merging :)

**Comment by kamilkisiela** [comment]
@helfer Done, I will wait for Uri to release it.

I really like the communication from past two days! All the changes goes smooooth

**Pull request merged**
