### PR TITLE
[super WIP] Make an entry point

### PR DESCRIPTION
**Pull request by stubailo**

### CODE REVIEW

**Comment by stubailo** [comment]
Note: if there are no error callbacks there is a forEach error

**Comment by stubailo** [comment]
Doesn't deal well with `null` results!

**Comment by mquandalle** [comment]
With that single entry point you should be able to define an opt-in list of `files` you want to include instead of the `exclude` list in the `tsconfig.json` file:

```diff
-  "exclude": [
-    "node_modules",
-    "typings",
-    "lib",
-    "test-lib"
+  "files": [
+    "typings/main.d.ts",
+    "src/index.ts",
+    "test/tests.ts"
   ]
 }
```

And by including the `typings/main.d.ts`, you can now remove the top `<reference path="../typings/main.d.ts" />` of every file.

**Comment by stubailo** [comment]
Oh, good idea!

**Comment by stubailo** [comment]
@jbaxleyiii don't worry about this yet - I'm just using `npm link` on this branch to test it in an app. I'm going to clean it up before merging.

**Comment by stubailo** [comment]
Redux dev tools are workingggg

screenshot 2016-03-22 17 53 47

I think being able to analyze exactly what queries are happening and what results are in the cache will be huge.

**Comment by mquandalle** [comment]
Making JavaScript great again™.

**Comment by stubailo** [comment]
Tests pass now, and I believe this can now be used as a real NPM package if someone were to publish it. Tried with `npm link`!

**Pull request merged**
