### PR TITLE
export addQueryMerging

### LINKED ISSUE #363: addQueryMerging not defined in exports
Tried to setup a custom network interface with query merging, and in the docs here: http://docs.apollostack.com/apollo-client/network.html#addQueryMerging

it says to import the ‘addQueryMerging’ function from apollo-client, however, its not declared in the exports of apollo-client

### PR DESCRIPTION
**Pull request by hammadj**
fixes #363

### CODE REVIEW

**Comment by stubailo** [comment]
Nice, perfect fix!

**Comment by stubailo** [comment]
Just have to wait for tests to pass and then I'll merge and publish. Do you mind adding a change log entry?

**Comment by hammadj** [comment]
done 👍

**Comment by stubailo** [comment]
Thanks!

**Pull request merged**
