### PR TITLE
Add basic interoperability with other Observable implementations

### LINKED ISSUE #149: Make it possible to use an existing observable implementation
For example, to easily integrate with RxJS.

### PR DESCRIPTION
**Pull request by martijnwalraven**
Closes #149.

### CODE REVIEW

**Comment by stubailo** [comment]
@martijnwalraven hey, I don't know how this happened, but it looks like you skipped the PR checklist, which included "add this to the changelog". Can you please add a changelog entry about this?

**Comment by stubailo** [comment]
@martijnwalraven also, the CI tests didn't pass on this PR.

**Comment by martijnwalraven** [comment]
@stubailo: Sorry I missed the changelog. I've added it to the 0.3.5 section because it was included in that release.

The tests passed on the CI but I missed the linter errors. Thanks for fixing these.

**Comment by stubailo** [comment]
Yeah no problem! Next time just wait until Travis is done before merging.

**Comment by martijnwalraven** [comment]
I actually did look at the CI results but figured there was something else wrong because the tests themselves passed. Should have taken a closer look at the logs and spotted the linter errors.

**Pull request merged**
