### PR TITLE
Implement basic network error handling

### LINKED ISSUE #78: Handle network errors
Right now, we handle GraphQLErrors just fine, but we don't have anything for network and runtime errors.

### PR DESCRIPTION
**Pull request by stubailo**
Extracted from @martijnwalraven's PR #97 

Fixes #78

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@stubailo so this removes the `handle.onResult` yes?

**Comment by stubailo** [comment]
Currently, it shims `onResult` to work: https://github.com/apollostack/apollo-client/pull/118/files#diff-748b449db1e130c8d777fa1ffa1e0725R293

But it might be kind of pointless to have that, since `subscribe` isn't much harder to call. Do you think it's OK to remove it?

**Comment by martijnwalraven** [comment]
@stubailo: Yeah, the shim was just to not to have to change the tests while I was working on it. Definitely should be removed.

**Comment by stubailo** [comment]
OK, going to do that now!

**Comment by stubailo** [comment]
Filed a docs issue: https://github.com/apollostack/docs/issues/12

**Comment by stubailo** [comment]
OK, looks like error handling works, we can implement the observable API on top of this.

**Pull request merged**
