### PR TITLE
Merge 631

### PR DESCRIPTION
**Pull request by stubailo**
TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)

### CODE REVIEW

**Comment by Akryum** [comment]
Could this allow us to use apollo with vuex instead of Redux?

**Comment by stubailo** [comment]
Not by itself, no. Does vuex use reducers?

**Comment by Akryum** [comment]
In vuex, we dispatch *Actions* (async, inpure functions, probably with api call) that can commit *Mutations* (sync, pure functions) to change the store state, which is accessed by *Getters* (also pure). Those can all be put inside a *Module* to split the store management in multiple mostly namespaced parts. I would say that a Reducer equivalent in vuex is a module with some actions/mutations.

**Comment by stubailo** [comment]
sounds to me like it should be possible to build a Redux-VueX adapter, so that you can pass vuex into apollo and from Apollo's perspective it will look just like Redux. What do you think?

**Comment by Akryum** [comment]
Sounds great! Maybe we could come up with a "standard" Apollo store interface that allow different kinds of store to be plugged in with an adaptation layer.

**Comment by stubailo** [comment]
Sure, I'm just not convinced we need anything other than the Redux API, which is quite simple!

But if you have any ideas, I'm definitely open to making those changes. Some constraints:

1. Apollo internally makes changes to data with actions and reducers, which probably isn't going to change
2. Apollo needs a callback for new store data

**Comment by jskorepa** [comment]
When do you expect to publish this on npm? It would be really awesome :+1:

**Comment by Akryum** [comment]
I just published the [Vue integration](https://www.npmjs.com/package/vue-apollo), I'll look into the vuex/apollo adapter soon.

**Comment by smolinari** [comment]
@Akryum - if you can get the vuex/apollo going, you'll be making one of my dreams come true! Thanks! :smile: 

Scott

**Pull request merged**
