### PR TITLE
Add payload size to the readme

### LINKED ISSUE #250: Add payload size info to the repo
When evaluating this library it's hard to know what the payload cost is.

Can you please include the built size of this project both gzipped and un-gzipped in the README to help developers making decisions?

Thanks!

### PR DESCRIPTION
**Pull request by stubailo**
Fixes #250

### CODE REVIEW

**Comment by owencm** [comment]
Just to confirm - that's 30KB before or after minification and gzipping?

**Comment by stubailo** [comment]
After. That's the metric people usually use a far as I can tell.

**Comment by owencm** [comment]
I find different projects list differently - would it be possible to edit to say "less than 30kb when minified and gzipped" to make it unambiguous?

**Comment by stubailo** [comment]
Sure, please submit a PR?

**Pull request merged**
