### PR TITLE
Add caching node_modules to TravisCI and AppVeyor

### PR DESCRIPTION
**Pull request by kamilkisiela**
**Travis-CI Total time**
before ~ 5 min 00 sec
after ~  3 min 30 sec

### CODE REVIEW

**Comment by stubailo** [comment]
@kamilkisiela I'm not quite sure how this works? Does it always reuse the previous node modules? What if the dependencies change?

**Comment by stubailo** [comment]
Wow the tests are so much faster now! Thanks!

**Comment by kamilkisiela** [comment]
@stubailo :)

**Comment by kamilkisiela** [comment]
@stubailo It works the same way as if you would have a repository cloned and node modules installed locally. 

So if a dependency changes from `0.3.X` to `0.4.X` then `npm i` will install the new module and `npm prun` will remove the old one from `/node_modules`.

After that, the `/node_modules` with a new contents will be saved to the cache.

**Comment by stubailo** [comment]
Hmm, this is good but CI used to have one extra positive effect, which is that it reinstalled all dependencies from scratch every time, meaning we got early warning when a dependency made an accidental breaking change. Perhaps Greenkeeper will take care of that, though!

**Comment by kamilkisiela** [comment]
Sort of trade off, but let's hope that dependant libraries won't bring any issues, they not suppose to because of Semantic Versioning but mistakes happen :)

**Comment by jbinto** [comment]
> Hmm, this is good but CI used to have one extra positive effect, which is that it reinstalled all dependencies from scratch every time, meaning we got early warning when a dependency made an accidental breaking change. Perhaps Greenkeeper will take care of that, though!

IMHO: If you really want to be safe, you should remove all version qualifiers (`^`, `>=`, etc) from `package.json` and let greenkeeper send you PRs for every minor version. 

Just because we have "semver" doesn't mean there aren't still bugs in software, despite people's best intentions.

**Comment by stubailo** [comment]
I don't think it's feasible to require exact versions in a package lots of people are using - we can do this for our dev dependencies, but users of the package need to be able to select their own versions of packages since they might have other constraints.

**Pull request merged**
