### PR TITLE
Add observable query current result

### PR DESCRIPTION
**Pull request by tmeasday**
<strike>This PR is rebased from https://github.com/apollostack/apollo-client/pull/635.</strike>

<strike>It also should not be merged until we've confirmed with RA.</strike>

### CODE REVIEW

**Comment by helfer** [comment]
@tmeasday would you like to see this merged+published before or after our refactor?

**Comment by tmeasday** [comment]
Ideally before I think. Let me hassle @jbaxleyiii again, as he was going to look at this stuff

**Comment by jbaxleyiii** [comment]
@tmeasday @helfer I'm so sorry for the delayed response on this. Especially since @tmeasday killed it here and with RA. I'm all for it!

**Comment by tmeasday** [comment]
Good to go then @helfer

**Comment by tmeasday** [comment]
@helfer - rebased against `master`. 

I actually ended up undoing part of this commit: https://github.com/apollostack/apollo-client/pull//commits/d852946123ccf2c6f5496a60924a67d89a5954c5

My rationale is that `QueryManager.getCurrentQueryResult` (and things in general) shouldn't need to look at the state of the *query* in order to figure out what the results of the query are. It's problematic for a few reasons, one in particular is: what if you call it *before* the query has even initialized, and the state is `null`? (which I do from `observable.currentResult()`).

The state of the query should be irrelevant to the results of the query. It's only the options etc of the query that determine the results. (The state drives `loading` though of course).

I'm not sure if we should remove the rest of the above commit though? Do we use `queryState.stopped` for anything else? Probably something for you and @stubailo to look at.

Obviously the tests from that #696 are super helpful to have, and still pass in this branch!

cc @rricard

**Comment by helfer** [comment]
@tmeasday yeah, I think we'll remove the `stopped` state in the refactor, but I'll publish a version with this first.

**Pull request merged**
