### PR TITLE
Remove AuthTokenMiddleware

### PR DESCRIPTION
**Pull request by abhiaiyer91**
Remove AuthTokenMiddleware for [issue #247](https://github.com/apollostack/apollo-client/issues/247)
TODO:
- [x] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by Poincare** [comment]
We should probably update the CHANGELOG since this is a user-facing change.

**Comment by stubailo** [comment]
Looks great to me!

**Comment by Poincare** [comment]
Travis CI failing on Node v5 for some reason?

**Comment by abhiaiyer91** [comment]
Weird right. Tests run fine locally

**Comment by stubailo** [comment]
Maybe some weird intermittent thing? Weird that the PR build passed. rerunning it.

**Pull request merged**
