### PR TITLE
Observable API

### PR DESCRIPTION
**Pull request by stubailo**
Reconstruction of @martijnwalraven's PR #97, on top of current master.

TODO:

- [x] Add tests for refetch before first fetch returns
- [x] Add tests for requests arriving in the wrong order on refetch

### CODE REVIEW

**Comment by stubailo** [comment]
@martijnwalraven I think I've reconstructed your whole PR on top of the two other features I merged -- let me know if I missed anything, but it looks like all the tests pass now!

**Comment by jbaxleyiii** [comment]
@martijnwalraven @stubailo https://github.com/reactjs/redux/pull/1632

**Comment by stubailo** [comment]
@jbaxleyiii that would be an awesome way to rebuild this functionality once it ships! I'm glad that observables and Redux are something that are going to be officially together soon :]

**Comment by stubailo** [comment]
Rebased on `master`

**Comment by stubailo** [comment]
Filed an issue about the Redux observable thing: https://github.com/apollostack/apollo-client/issues/123

**Pull request merged**
