### PR TITLE
failing tests for #1123

### PR DESCRIPTION
**Pull request by krksgbr**
failing tests for #1123

Looked into the issue for the case when optional query variables are causing trouble when trying to update a previous query result. In `fetchMore.ts` when making a query while omitting an optional variable the following error is thrown: 

```
 Error: The inline argument "optionalVar" is expected as a variable but was not provided.
      at valueToObjectRepresentation (node_modules/graphql-anywhere/lib/src/storeUtils.js:40:19)
```

In `mutationResults.ts` when trying to update a query result after a mutation, the error is swallowed somewhere and the previous result is not updated.

I merely duplicated existing cases and added variables to them which I doubt is the right approach, so let me know how this could be done better.

### CODE REVIEW

**Comment by helfer** [comment]
@krksgbr thanks for the PR! 🙂  I think this should be fixed by another PR from @calebmer that I just merged, so please rebase this on master and check if the test still fails.

**Comment by calebmer** [comment]
I was going to put these in https://github.com/apollostack/apollo-client/pull/1174/files, but only one of the tests pass. The other has to deal with reading from the store, so without a change to `graphql-anywhere` it still fails.

**Comment by helfer** [comment]
@calebmer ok, makes sense! Let's make the necessary changes in graphql-anywhere.

**Comment by calebmer** [comment]
@helfer submit a PR to get this in `graphql-anywhere` https://github.com/apollostack/graphql-anywhere/pull/30 👍

**Comment by calebmer** [comment]
Looks like the tests are passing now 🔥

I’m going to update our dependency on `graphql-anywhere` to `2.1.0` (the release with the fix) and then merge 👍

**Pull request merged**
