### PR TITLE
Test case for rollup circular dependencies.

### PR DESCRIPTION
**Pull request by voodooattack**
TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by voodooattack** [comment]
Signed!

**Comment by helfer** [comment]
@voodooattack Thanks! Do you know if the dependency between ApolloClient.ts, QueryManager.ts and ObservableQuery.ts are the only ones?

I honestly think that this is something that rollup should fix, because circular dependencies are a well-known and pretty normal thing in ES6, but if there's something simple we can do to make it work in the meantime, I'm happy to go along with it 🙂

**Comment by voodooattack** [comment]
@helfer I have no idea, I switched to webpack 2 beta yesterday (which also has tree-shaking) and the problem disappeared altogether. I think rollup needs to fix this though. I'm migrating over two dozen packages to webpack right now and it's not pretty.

**Comment by helfer** [comment]
@voodooattack if you no longer need this, can we close the PR?

**Comment by voodooattack** [comment]
Yes, sorry. Closing it now.

**Comment by stubailo** [comment]
@helfer I think the related issue is that we don't publish the ES2015 module build, so rollup users need to use the common js plugin which doesn't support circular deps.

**Comment by helfer** [comment]
@stubailo so what's the solution? Remove all circular dependencies? That's going to be quite tricky I think. And as you mentioned in #731, people need to use the commonjs plugin anyway if we depend on modules that are not ES6.

I think it's fine to have the test here, but until we have a solution, I'd rather keep it closed.

**Pull request closed without merging**
