### PR TITLE
expose partial in ObservableQuery.currentResult

### PR DESCRIPTION
**Pull request by machard**
This PR just exposes the `partial` property when calling `ObservableQuery.currentResult`.

### CODE REVIEW

**Comment by helfer** [comment]
@machard what problem does this PR solve?

**Comment by machard** [comment]
@helfer 

related to this PR that i am preparing for react-apollo : https://github.com/apollostack/react-apollo/compare/master...machard:review-skip-2
I will make a good explanation of what it solves when publishing to github.

to answer you in the apollo-client context, look at that for example:
1) you create a request with forceFetch=true noFetch=false
2) when calling currentResult (like it's done in react-apollo) you have loading = true => loading = false
3) if you refetch it (when noFetch goes to true then back to false for example) you will have again loading = true => loading = false BUT i would like to be aware that the result is already full (by exposing partial that would be false in this case). it's kind of emulating the stale property in relay https://facebook.github.io/relay/docs/guides-ready-state.html#onreadystatechange (partial=false && loading = true <=> stale = true && loading = true)

the user use case is that you don't want to redisplay a loading state when updating a query in the background (each time you go back to the screen for example). you want to display the result as soon as partial=false.

**Comment by helfer** [comment]
@machard okay, thanks! I'll take a look after the weekend.

**Comment by helfer** [comment]
@machard thanks for the PR! I can see how this could potentially be useful, and I don't think it will lead to any unnecessary re-renders, but it's a change in the external API, so I've changed the base to the 0.6 branch.

**Comment by helfer** [comment]
Before I can merge it, please make sure there's an entry in the changelog, and a corresponding PR to the docs where necessary. If you don't delete the PR template next time, it'll actually tell you what needs to be done :wink:

**Comment by machard** [comment]
ok 'ill do that

**Comment by machard** [comment]
@helfer  i updated changelog, however i am not sure what you expect me to do for the docs as it seems it gets the data from the AC source ?
https://github.com/apollostack/core-docs/blob/e20246bb4dc8ca8ea77719274e0838f43bbd08a7/source/apollo-client-api.md#L51
http://dev.apollodata.com/core/apollo-client-api.html#ApolloCurrentResult

**Comment by helfer** [comment]
@machard thanks!

Yes, that's right, the docs are generated. I just have to figure out how we used to do that ... 🤔 
What would be very useful though is if you added docstrings to the ApolloQueryResult so that the docs will actually have an explanation for what each of the members in ApolloQueryResult is. Could you do that? Shouldn't take more than 5 minutes. 🙏

**Comment by machard** [comment]
@hellfer, i was going too right now but i don't see other data structures with doc string so I am not sure what the syntax :/

**Comment by helfer** [comment]
@machard As far as I know you can only document functions, so for this one you should document the return value of `watchQuery`. Here is some more info on typedoc: http://typedoc.org/guides/doccomments/

**Comment by machard** [comment]
@helfer done, and i rebased

**Comment by helfer** [comment]
@machard Thanks a lot, it's merged! Btw, we're planning to get rid of partial responses for 1.0, and return only valid GraphQL responses or nothing for queries.

**Pull request merged**
