### PR TITLE
Use Yarn

### PR DESCRIPTION
**Pull request by kamilkisiela**
Same thing as with `jest`. Do you want to use it?
- [x] #849 to be merged (AppVeyor throws error)

### CODE REVIEW

**Comment by stubailo** [comment]
Don't we want to make sure we always get the newest versions of everything on CI tests? I feel like it's actually better to not have the features of Yarn here, but I could be convinced otherwise.

**Comment by kamilkisiela** [comment]
@stubailo `apollo-client`'s CI configuration enables `node_modules` caching so you use still don't use latest, only those that fit requirements

I updated travis in #865 to run `npm prune` before `npm install` so it will remove all unused packages before compiling `apollo-client` (`prepublish` script).

I created this PR just to open the discussion :)

**Comment by helfer** [comment]
@kamilkisiela is there a compelling reason to switch to yarn at the moment? What are the pros and the cons?

**Comment by stubailo** [comment]
Yeah, I don't think this benefits us a lot.

**Comment by marvinhagemeister** [comment]
Moreover the recent yarn release 0.17.0 has lots of regressions. The obvious advantage of yarn is install speed. But without a stable release process or more tests to catch regressions, I'd be cautious about using it as the default.

**Pull request closed without merging**
