### PR TITLE
Strip apollo directives

### PR DESCRIPTION
**Pull request by rricard**
#TODO:

- [x] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

Linked to the work of #350

### CODE REVIEW

**Comment by rricard** [comment]
@stubailo How are we on this one ? I need to have it merged in order to continue my work on the infinite pagination ...

**Comment by rricard** [comment]
I'll start by rebasing 😉

**Comment by rricard** [comment]
Rebasing done ✅

**Comment by stubailo** [comment]
@amandajliu is working on a refactor of query transforming right now, to generalize it so that this code is better.

**Comment by rricard** [comment]
Well, ok, ping me when the refactor is ready so I can work on this again ...

**Comment by stubailo** [comment]
This should be refactored on top of #412, I think @amandajliu can do it!

**Comment by rricard** [comment]
@stubailo: can do it today

**Comment by rricard** [comment]
Started by rebasing ...

**Comment by rricard** [comment]
@stubailo: done ✅

**Comment by rricard** [comment]
just rebased again

**Comment by rricard** [comment]
@stubailo any ETA for a merge here ? I need it merged to continue splitting the PRs and I need the overall feature quite fast.

**Comment by stubailo** [comment]
I'm closing this because I'm not sure we need it anymore? Could reopen if we still do.

**Pull request closed without merging**
