### PR TITLE
Update types against GraphQL 0.8.2 and @types/graphql

### LINKED ISSUE #927: Change typed-graphql to @types/graphql
Created a PR against DefinitelyTyped repository to update GraphQL typings to at least 0.8.0 (now I need bed). Opening this issue to track it so we can update here when it's in: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12735

### PR DESCRIPTION
**Pull request by intellix**
TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

closes #927 
depends on: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12767

Currently getting a few errors with GraphQLError type as the @types/graphql is saying some fields are required. Some changes are needed before that gets merged and then this can be.

Just wanted to push some work before bed and someone else spends the same time on this :)

### CODE REVIEW

**Comment by intellix** [comment]
Also depends on this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12800 to fix the Error tests

**Comment by intellix** [comment]
That fixes all of the errors throughout compilation. I'm still getting errors about Namespace `_` not having some exported members but that'll not be to do with anything I did.
When DefinitelyTyped#12800 is merged, this is good to go

**Comment by intellix** [comment]
Also requires: https://github.com/apollostack/graphql-anywhere/pull/16

**Comment by intellix** [comment]
all depended branches were merged. This should be ready

**Comment by helfer** [comment]
@intellix Awesome! Do you have time to rebase/merge the branch? As soon as that's done, we should be ready to drop typed-graphql.

**Comment by intellix** [comment]
Your wish is my command! have fun re-reviewing :P

**Comment by stubailo** [comment]
Closing in favor of #1041

**Pull request closed without merging**
