### PR TITLE
rename action types

### PR DESCRIPTION
**Pull request by abhiaiyer91**
Prefix Action Types with `APOLLO_`

[#210](https://github.com/apollostack/apollo-client/issues/210)

TODO:

- [x] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by stubailo** [comment]
Looks great!

**Comment by stubailo** [comment]
Can you add to the change log please? And in the future tonight be easier to keep the default checklist.

**Comment by abhiaiyer91** [comment]
Will get to it when i am home! Where is the default checklist?

**Comment by stubailo** [comment]
https://github.com/apollostack/apollo-client/blob/master/.github/PULL_REQUEST_TEMPLATE.md

It should show up as the default description when you make a new PR.

**Comment by abhiaiyer91** [comment]
@stubailo All done thank you!

**Comment by stubailo** [comment]
Looks good to me, let's merge after CI passes!

**Comment by stubailo** [comment]
Published in 0.3.9!

**Pull request merged**
