### PR TITLE
Back to use noImplicitAny

### PR DESCRIPTION
**Pull request by kamilkisiela**
@stubailo

### CODE REVIEW

**Comment by kamilkisiela** [comment]
Waiting for nitintutlani/typed-graphql#25

**Comment by DxCx** [comment]
Hi @kamilkisiela,
The package renamed
Try npm install typed-graphql

**Comment by kamilkisiela** [comment]
@DxCx thanks

**Comment by stubailo** [comment]
Awesome, thanks!

**Pull request merged**
