### PR TITLE
Use Jest for testing

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@stubailo @helfer Should I move on with this or you don't want to use `jest`?

**Comment by kamilkisiela** [comment]
Travis throws some errors but only because there are some old node modules with typings. They come with that `node_modules` directory caching. We can clean the cache inside travis dashboard.

There are still whole bunch of failed tests, that's why I'm asking if you guys are going to use `jest` as a test tool.

**Comment by stubailo** [comment]
I had a lot of trouble working with jest in react-Apollo, so I'm not sure. For example, you can't use "it.only" to just run one test, or use a regex to filter tests as far as I can tell?

**Comment by kamilkisiela** [comment]
That's true! :)

**Comment by stubailo** [comment]
@jbaxleyiii do you have any concrete advantages you've found from using Jest?

**Comment by jbaxleyiii** [comment]
@stubailo testing speed, a great watch mode, and a very active development team are part. For react Apollo the biggest bit was react native support out of the box. 

Jest is the preference of our team but nothing I would say is a MUST switch. We use snapshots lot for things like UI regression testing but again, not needed here.

**Comment by helfer** [comment]
I think we'll pass on Jest for now, I just don't see a compelling reason to switch.

**Pull request closed without merging**
