### PR TITLE
Fix #713

### LINKED ISSUE #713: Consider moving @types packages from devDependencies to dependencies
The rationale is discussed here:
https://github.com/Microsoft/types-publisher/issues/81

This doesn't prevent my app from running, but the TS errors are pretty annoying especially because they break HMR (with the overlay configured) as shown below:

apollo ts declaration dependencies_censored

### PR DESCRIPTION
**Pull request by antmdvs**
TODO:

- [X] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [X] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass
- [X] Update CHANGELOG.md with your change
- [X] Add your name and email to the AUTHORS file (optional)
- [X] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

Moved @types packages from devDependencies to dependencies per #713

### CODE REVIEW

**Comment by poloagustin** [comment]
I hope this gets merged soon. I'm stuck with these referenced issues 😔

**Comment by helfer** [comment]
It seems we're between a rock and a hard place here, because adding typings to dependencies makes it impossible to install Apollo Client for people who are behind a firewall and only have access to a restricted set of packages... I'm honestly not sure what the best solution is here.

**Comment by poloagustin** [comment]
@helfer Sorry, I totally missed that you are explicitly saying you use Typescript in your project. What if we add a Troubleshoot section for now that specifies the @types dependencies for typescript projects.
I also feel that the @types dependencies shouldn't compromise non-Typescript projects.

**Comment by helfer** [comment]
@poloagustin yeah, I think it would be a great idea to add a "troubleshoot" section to the README. Can you make a PR for that? 🙂

**Comment by poloagustin** [comment]
sure! 👍

**Comment by stubailo** [comment]
So should we close this then? And just document the set of types people need to add?

**Comment by tuurbo** [comment]
There are a lot of types to maintain. Could we have a seperate package, something like ```apollostack/apollo-client-types``` or maybe combine them with ```@types/apollo-client```. Idk how it works

**Comment by stubailo** [comment]
@tuurbo how do we publish `@types/apollo-client`? Do we have to go talk to someone to get access to that package name?

**Comment by tuurbo** [comment]
@stubailo Have no idea how it works sorry :/

**Comment by tuurbo** [comment]
@stubailo Looks like I found the docs https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by DxCx** [comment]
hi @helfer, what about state @types as optionalDependcies.
this was non-typescript users don't need to install them,

**Comment by helfer** [comment]
@DxCx yeah, maybe that would be a workable solution for now!

**Comment by poloagustin** [comment]
like this #772 ?

**Comment by helfer** [comment]
Closing this now, since we merged #772

**Pull request closed without merging**
