### PR TITLE
[On hold] Fetch more / Infinite Scroll

### PR DESCRIPTION
**Pull request by rricard**
Adds a fetchMore method able to fetch new data and concatenate it into the store, performing, that way, an infinite scroll behavior!

TODO:

- [x] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

- [x] change `concatPaths: Array<string>` to `paginationParameters: Array<string>`, that way suppressing for special paths those parameters from the store ids. (ex: instead of `ROOT_QUERY.allPosts({cursor: 'x', type: 'y'})`, if `paginationParameters: {'ROOT_QUERY.allPosts': ['cursor']}` is set, it will only be `ROOT_QUERY.allPosts({type: 'y'})`
- [x] Implement correct resolution of paths
- [x] Squash!
- [x] `paginationParameters` => `quietArguments`
- [x] Backwards concat possible
- [x] Add directive for pagination !
- [x] Add a per-directive merge option
- [x] Add a directive selection in the fetch more to avoid fetching more of everything
- [x] fetch more can override query-level opts
- [x] embed into the directive common merging use cases: `append/prepend/sort`
- [x] Make sure is correctly wired (`fetchMore()` to the public API, `paginationParameters` everytime there is some store access & `fetchMore everytime we're doing a query)
- [x] Do a proper system to handle directives (right now it's clearly hacky) => **REFACTOR!**
- [x] So do MORE TESTS and/or integrate with existing tests to take `paginationParameters` in account.
- [x] Directive removal before sending the query to the server! *OR* PR on the server to support the directive there (by adding it to the schema! Maybe somewhere in `graphql-tools`)
- [ ] Add it to the docs!

## Basic usage example:

```js
let latest_name = null;
const subscription = client.watchQuery({
  query: gql`
    all_people(latest_name: $latest_name, type: $type) @apolloFetchMore {
       name
    }
  `,
  quietArguments: ['latest_name'],
  variables: {
    type: 'Jedi',
    latest_name: null,
  },
}).subscribe({
  next(result) {
    console.log(result);
    // First value => {all_people: [{name: 'Luke SkyWalker'}]}
    // Second value => {all_people: [{name: 'Luke SkyWalker'}, {name: 'Obi-Wan Kenobi'}]}
    const new_latest_name = result.all_people[result.all_people.length -1];
    if(new_latest_name !== latest_name) {
      latest_name = new_latest_name;
      subscription.refetchMore({latest_name});
    }
  }
});
```

## Advanced usage example:

```js
let latest_name = null;
const subscription = client.watchQuery({
  query: gql`
    messages(cursor: $chatCur) @apolloFetchMore(name: "messages") {
      content
      replies @apolloFetchMore(name: "replies") {
         content
       }
    }
  `,
  quietArguments: ['cursor'],
  variables: {
    chatCur: null,
  },
  mergeResults: {
    messages: (oldArr, newArr) => [].concat(newArr, oldArr),
  }
}).subscribe({
  next(result) {
    console.log(result);
    setTimeout(() => {
      subscription.refetchMore({targetedFetchMoreDirectives: ['replies']});
    }, 60000);
    setTimeout(() => {
      subscription.refetchMore({targetedFetchMoreDirectives: ['messages']});
    }, 10000);
  }
});
```

## Advanced usage example with directives only!:

```js
let latest_name = null;
const subscription = client.watchQuery({
  query: gql`
    messages(cursor: $chatCur) @apolloFetchMore(name: "messages", quiet: "cursor", prepend: true) {
      content
      replies @apolloFetchMore(name: "replies") {
         content
       }
    }
  `,
  variables: {
    chatCur: null,
  },
}).subscribe({
  next(result) {
    console.log(result);
    setTimeout(() => {
      subscription.refetchMore({targetedFetchMoreDirectives: ['replies']});
    }, 60000);
    setTimeout(() => {
      subscription.refetchMore({targetedFetchMoreDirectives: ['messages']});
    }, 10000);
  }
});
```

### CODE REVIEW

**Comment by rricard** [comment]
Followup to #335

**Comment by stubailo** [comment]
Can you rebase on master, as well?

**Comment by rricard** [comment]
yep, let me fix a test first

**Comment by rricard** [comment]
I already rebased minutes ago ...

**Comment by rricard** [comment]
And ... all done!

**Comment by stubailo** [comment]
OK @rricard are you OK if I just work on this and maybe merge it?

**Comment by stubailo** [comment]
Just really excited to deliver this feature to our app team and see if they can use it in Galaxy.

**Comment by rricard** [comment]
No problem! I started that work so I could use the feature so that's cool if you take it from here. If you don't understand something I did, ping me here or on slack.

**Comment by stubailo** [comment]
Well I've got about 6 hours today to try to finish this and #336, let's see if I can get it done! Days without meetings don't come by too often :]

**Comment by stubailo** [comment]
So I think I'm going to remove a few things, in particular the sorting options in the directive. I think I'd rather add less stuff for now, and add more options later if it turns out the minimal approach is not convenient.

**Comment by jbaxleyiii** [comment]
@stubailo do you have an ETA for this? I'd rather not hack together a solution for something I need to ship if this is close!

**Comment by stubailo** [comment]
I'd guess merge by Tuesday. I was planning on doing it Friday but didn't get it finished.

**Comment by rricard** [comment]
Ok, so I bumped apollo's max Gzipped file to 36kB.

**Comment by stubailo** [comment]
FYI, rebased on `master`.

**Comment by rricard** [comment]
okay pulling the rebased version

**Comment by rricard** [comment]
@stubailo not a fan of your directive validation simplification. The goal of that was to be able to let the user integrate custom directives later... If we use this hardcoded validation (that I implemented at first as well) this will prevent easily inserting new custom and easily validable directives later.

**Comment by stubailo** [comment]
OK I have one concern right now: how does polling/refetch work with this pagination model?

- `refetch`: I think it's OK if refetch just fetches the original query, and ends up throwing away the paginated data completely. For the use cases I can imagine, refetch ends up basically "restarting" the pagination from the beginning.
- `pollInterval`: I feel like the whole point of pagination is to avoid loading all of the data at once, so it would be odd to use polling with it. The one use case I can think of is polling for new data in the list - let's say you have a comment thread and you want to display new comments as they come in. But I feel that this might be a pretty uncommon use case so maybe we can just disable the combination of `fetchMore` and polling.

**Comment by stubailo** [comment]
@rricard honestly I don't think it's a good idea to write a general validation system if we aren't going to use it right now. Who knows what kind of validation we will need in the future? Maybe we won't need any general validation, in which case this solution is good, or maybe we will need very complex validation with dependencies between arguments, in which case we can't predict what we will need.

**Comment by rricard** [comment]
pollinterval will work like a refetch like it does right now. I don't know if we can customize that in order to do paginated polling

**Comment by stubailo** [comment]
@rricard I feel like it would be weird if someone set up a pollInterval, then scrolled down/loaded more data, and then the data was thrown away because the polling interval was hit. I'd be in favor of throwing an error if polling and fetchMore are used in one query, what do you think?

**Comment by rricard** [comment]
for the validation system: I will soon have validation needs but fair enough, I'll do an another PR when the need will be imminent. Basically here is my thought process: if graphql-js allows to add custom directive validation, we should be able to do that (or let that happen) as well on the client. So if you don't want anything to do with with validating directives, maybe just let unknown directives pass through (and let the server validate them)

**Comment by rricard** [comment]
pollInterval+pagination won't play well together I agree. I don't think they should. When you take control with a fetchMore, you now become responsible for loading stuff (and merge it) in the order you need it.

**Comment by stubailo** [comment]
Personally I think it would be fine to let through unknown directives. This, combined with custom network interfaces, could be an easy way to implement `@defer`, `@stream`, etc.

Do you think directive validation via static analysis (ESLint etc) is sufficient? Or maybe it can be something that is done only in a development build? I feel like it can get pretty complicated and it seems odd to do all of that work and load all of the logic at runtime.

> pollInterval+pagination won't play well together I agree. I don't think they should. When you take control with a fetchMore, you now become responsible for loading stuff (and merge it) in the order you need it.

Cool, let's make it throw an error somehow.

**Comment by stubailo** [comment]
Let me know if you think this is reasonable, but my goal is to merge something that is as minimal and flexible as possible, then add additional options and built-in stuff once people have a chance to try it out. This is why I removed some of the things you had already implemented like special sorting options, prepend, etc, since I think they are covered by the `mergeResults` function.

**Comment by rricard** [comment]
@stubailo I think we do agree on both points:

- directives: for now just let them through. I indeed wanted to explore @defer @stream and @live Having eslint validation would be great indeed to solve that. That would put as well validation directly in the IDE.
- agree with the error, triggering a refetchMore if pollInterval is defined should trigger a warning / invariant violation

**Comment by rricard** [comment]
I agree with the more minimalist @apolloFetchMore directive as well. i went a bit crazy there

**Comment by stubailo** [comment]
In that vein, right now `quiet` can be specified in `WatchQueryOptions` or in the query document. Do you think it would be enough if they were only specified in the directive? That seems better to me since it's closer to the field itself. I'm curious how you would prefer to do it in your app.

**Comment by rricard** [comment]
I would use quiet at query level and not in the directive personally, all of my pagination fields are the same throughout the schema. If I could even put that at client-level that would be even better to me. I added that on the directive to handle custom situations of pagination.

**Comment by rricard** [comment]
Ok, so do you want me to do:

- error/warning on refetchMore on pollInterval
- let through unknown directives

or are you already on it ?

**Comment by stubailo** [comment]
@rricard that's a good point, that it's easier to share stuff if it is in JS-land vs. in query land. In some sense making the directive as minimal as possible is probably the way to go since that's the "weirdest" thing.

When you're talking about client-level, I guess you're not worried about the idea that something like `latest_name` or `cursor` or whatever could be used in a non-pagination context? I guess it would only apply when calling `fetchMore` so maybe it doesn't matter.

Hmm... now that I realize that quiet fields are only ignored when calling fetchMore, it seems like client-global options might be a good idea. That would certainly make stuff like Relay pagination simpler.

> or are you already on it ?

I think I'm going to go to sleep at this point, it's pretty late here. I think the last things are:

1. Pass through unknown directives
2. Remove `@apolloFetchMore` before sending query to the server
3. Error/warning on poll and fetchMore
4. Potentially remove `quiet` argument on the directive
5. Add a few more tests, specifically it would be nice to see one with a Relay connection and one with a refetch after pagination
6. If you think it's a good idea, add a `paginationArguments` option to `ApolloClient` constructor (personally I think `quiet` is a bit too generic for this? but maybe `pagination` is too limited? not sure)

I'm probably going to come back and do some more work on this tomorrow morning.

**Comment by rricard** [comment]
> I think I'm going to go to sleep at this point, it's pretty late here.

Yep, that's what I thought 😉 ! Thank you for helping me on this. Sleep well 🌙 !

> Hmm... now that I realize that quiet fields are only ignored when calling fetchMore, it seems like client-global options might be a good idea.

Nope, theay are **ALWAYS** ignored, otherwise the first query without `fetchMore` won't do the thing we want. So they will be **ALWAYS** ignored. Which is still in my opinion a good thing for relay pagination fields for instance (or in my own schema: `cursor` & `limit`)

**Comment by rricard** [comment]
> 2. Remove @apolloFetchMore before sending query to the server

Don't really know how to do that 😕 . Never mind, I'll look for it...

**Comment by stubailo** [comment]
If there is something you don't know how to do I can do it tomorrow.

**Comment by rricard** [comment]
@stubailo: I'll let you naming and api decisions. Sleep on it, find the solution tomorrow!

**Comment by rricard** [comment]
@stubailo: 
[0001-Attempt-at-stripping-away-apolloFetchMore-directive-.patch.txt](https://github.com/apollostack/apollo-client/files/349550/0001-Attempt-at-stripping-away-apolloFetchMore-directive-.patch.txt)

 This patch is as far as I managed to go to strip directives before hitting the network interface. It has to be done after query init but before sending. I didn't managed to get the right moment to do that it seems since my tests with `@apolloFetchMore` fail miserably.

**Comment by rricard** [comment]
This is a bit hacky anyway, i'll let you manage that.

**Comment by rricard** [comment]
Ok here is the state of it now:

- [x] Pass through unknown directives
- [ ] - _attempted_ - Remove @apolloFetchMore before sending query to the server
- [x] Error/warning on poll and fetchMore
- [ ] - _decision needed_ - Potentially remove quiet argument on the directive
- [ ] Add a few more tests, specifically it would be nice to see one with a Relay connection and one with a refetch after pagination
- [ ] Add `quietArguments` to ApolloClient constructor
- [ ] - _decision needed_ - Rename `quietArguments` to `paginationArguments` ?

**Comment by rricard** [comment]
@stubailo: Ok, I tried a lot of stuff. I can't get the tests going correctly and I have some other stuff to take care of. Here is my latest patch on removing before sending to server: 
[0001-Remove-directives-before-sending-to-network.patch.txt](https://github.com/apollostack/apollo-client/files/350110/0001-Remove-directives-before-sending-to-network.patch.txt)

**Comment by rricard** [comment]
Maybe just add it to the graphql-tools, and document that for people not using them, it's just, after all:

```graphql
directive @apolloFetchMore on FIELD
```

**Comment by stubailo** [comment]
I'll figure out how to remove it - it's critical that people don't have to use our server with this feature.

**Comment by rricard** [comment]
Ok, @stubailo, it's done! Had to just go slower and structure things more correctly. Now the annotation is never sent to the server but is still usable from within the client (especially when writing the store. I managed to get that by transforming the query as immutably as I could.

**Comment by rricard** [comment]
Now we just need to figure out what we finally want: 
- Do we keep `quiet` on the directive ? (I would say yes because it can give a per-field control if you are doing something really complex)
- Do we rename `quietArguments` and how if yes ? (I would say something like `storeIgnoredArguments` but not `paginationArguments` => too specific)

**Comment by stubailo** [comment]
> Now the annotation is never sent to the server but is still usable from within the client (especially when writing the store.

Thanks for that - I think your solution is great, basically what I was trying to do as well.

> Do we keep quiet on the directive ? (I would say yes because it can give a per-field control if you are doing something really complex)

Another way we could get per-field control is if we made the `quietArguments` option in JavaScript also take a dictionary of names, which would be more consistent with how `mergeResults` works now. That way, you can pass around these arguments as JavaScript variables rather than adding them to the query every time.

> Do we rename quietArguments and how if yes ?

My main concern here is if someone new is reading the code, and sees "quietArguments", I think they would get pretty confused. I guess at that point you could go read the docs, but it seems like something even like "paginationArguments" or maybe even "ignoredArguments" or similar actually gives you an idea of what it's for.

**Comment by rricard** [comment]
Ok, I need to leave work so I may let you do that. I agree with what you said 👍

**Comment by stubailo** [comment]
Todos for me:

- [ ] Remove `quiet` on the directive
- [ ] Don't put `mergeResults` functions in the store, since then it won't be serializable
- [ ] Make `quietArguments` able to be a dictionary, like `mergeResults`
- [ ] Rename `quietArguments` to something more descriptive

**Comment by stubailo** [comment]
Hey, so to be honest, I'm having a really really hard time reasoning about the possible implications of all of these changes, especially because there are a lot of things together. I think this PR kinda became too big for its own good.

I think this is mostly my fault, because I didn't put in effort at the beginning to encourage splitting this into smaller chunks of work -- I'll make sure it doesn't happen again in the future.

I'm going to try a different approach for this feature, which is to try to split this up into the smallest PRs possible, each with their own tests etc.

For example:

1. Passing through custom directives
2. Stripping apollo client-only directives
3. Getting access to apollo client-only directive information inside write/read to store functions
4. `fetchMore` with no options, and only append
5. `fetchMore` with custom behaviors, and only one per query
6. `fetchMore` with multiple `apolloFetchMore` directives per query

For each of those, it will be a lot easier for me to reason about whether we have good test coverage, if there are weird edge cases, etc.

Sorry for anyone who was relying on this feature getting merged this week - I'd rather take a step back now than merge something that I don't fully understand the implications of.

**Comment by stubailo** [comment]
Here's the first PR, to not throw on unknown directives: https://github.com/apollostack/apollo-client/pull/372

**Comment by rricard** [comment]
@stubailo: we'll wait. But let me help you though, I'll try to break down that today.

**Comment by rricard** [comment]
@stubailo: I think that's a pretty great decision in the long run. Even in order to get this merged, I think that's a good idea since it will make the review easier therefore faster.

**Comment by rricard** [comment]
@stubailo: made a PR for stripping apollo directives

**Pull request closed without merging**
