### PR TITLE
Create and expose MutationOptions ;)

### PR DESCRIPTION
**Pull request by kamilkisiela**
Would help a lot with things like this
https://github.com/apollostack/angular2-apollo/issues/141#issuecomment-257858263

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@helfer done

**Comment by kamilkisiela** [comment]
@helfer :D that's right, forgot to rename it :D

**Comment by kamilkisiela** [comment]
@helfer now should be okay, long day...

**Comment by helfer** [comment]
Thanks, lgtm!

**Pull request merged**
