### PR TITLE
Add batcherPollInterval as an option to ApolloClient

### LINKED ISSUE #394: Allow app developer to set batcher polling interval
We should expose a way for the application developer to set the batcher poling interval and give it a sensible default rather than making it something that Apollo Client orders.

### PR DESCRIPTION
**Pull request by Poincare**
Adds an option that lets the application developer specify the width of the batcher's polling interval. Fixes #394 

TODO:

- [x] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by stubailo** [comment]
I'm curious - what spurred the need for this change? Was this a result of Galaxy investigation?

**Comment by Poincare** [comment]
Yup, the galaxy ui. It became pretty evident that tweaking the batcher polling interval on a per-app basis would be useful.

**Comment by stubailo** [comment]
What interval made sense for galaxy?

**Comment by Poincare** [comment]
10 ms seems to work okay for Galaxy but as I play around with it more, I'll have a better idea.

**Comment by stubailo** [comment]
Let's rename this to `batchInterval`.

**Comment by Poincare** [comment]
Good call, fixed @stubailo

**Pull request merged**
