### PR TITLE
Exports mockInterfaces

### PR DESCRIPTION
**Pull request by linonetwo**
https://github.com/apollostack/apollo-client/issues/905

I update the import path of tests.

I don't know how to add this to CHANGELOG since changes there are all in some versions...

- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by kamilkisiela** [comment]
Super helpful to UI integrations!

**Comment by linonetwo** [comment]
What does 「This branch has conflicts that must be resolved」? I did something wrong?

**Comment by helfer** [comment]
@linonetwo it means you have to run `git fetch` and then `git merge origin/master` (or rebase, if you know how that works) and then resolve the conflicts in `src/index.ts`. You are getting this error because there have been some changes to the master branch since you started your PR.

I also talked to @stubailo recently, and we have some concerns around importing things from subdirectories like `test/mockNetworkInterface`. Our preferred approach would be to break this kind of testing functionality out into a separate package, and import it from there (see #527). I know that's a lot more work, but maybe Kamil - our TypeScript guru - could help out setting up the typescript project for that?

@kamilkisiela would you be able to help out with this? ^

**Comment by kamilkisiela** [comment]
@helfer I've made a starter kit so you can reuse it in any of your projects

https://github.com/kamilkisiela/typescript-project

**Comment by kamilkisiela** [comment]
@helfer https://github.com/apollostack/apollo-test-utils

**Comment by helfer** [comment]
@kamilkisiela fantastic!

@linonetwo could you move the mockNetworkInterface to the package that Kamil just created and change this PR here (or open a new one) to make Apollo Client use that package? That would be really great! :pray:

**Comment by kamilkisiela** [comment]
@linonetwo message me if you need any help

**Comment by linonetwo** [comment]
I'm working on this. There will be a new PR so I'm going to close this.

I'm moving some tests from 'apollo-client' and 'react-apollo' to 'apollo-test-utils/tests', try to cover usages.
And I found that utils likes 'observableToPromiseAndSubscription' is related to some use cases of mockQueryManager. 

So I decided to move 'apollo-client/test/utils' together with it.

**Comment by linonetwo** [comment]
@kamilkisiela 

1. How to solve it if it is saying:

  4 failing

  1) HTTPBatchedNetworkInterface should correctly return the result for a single request:
     ReferenceError: fetch is not defined
      at HTTPBatchedNetworkInterface.batchedFetchFromRemoteEndpoint (C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:79:16)
      at C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:41:30

... same 3 failing

While there is truely a ```import 'whatwg-fetch';``` in apollo-client/transport .

2. There used to be a weird usage in tests/batchedNetworkInterface :
```javascript
    fetch = fetchFunc || createMockFetch({
      url,
      opts: merge({
        body: JSON.stringify(printedRequests),
        headers:  {
          Accept: '*/*',
          'Content-Type': 'application/json',
        },
        method: 'POST',
      }, opts),
      result: createMockedIResponse(resultList),
    });
```
Where ```fetch =``` will cause:
```
 4) HTTPBatchedNetworkInterface opts should be able to modify request headers and method (#920):
     ReferenceError: fetch is not defined
      at assertRoundtrip (C:\Users\lindo\Desktop\repo\apollo-test-utils\dist\tests\batchedNetworkInterface.js:23:15)
```

so I simply change it to : 
```javascript
fetchFunc || createMockFetch({ ... }) // no  fetch =  now!
```
Is that OK? I can't understand why use ``` fetch = ```there.

3. I use flowtype in my daily work, so I'm used to ```import xxx from 'xxxxx';``` but not ```import xxx = require('xxxxx');``` , From the code in this repo, I think using both of them is OK now. Which do you prefere? I will choose to use the one that close to the mainstream typescript usage.

**Comment by helfer** [comment]
@linonetwo @kamilkisiela how is this progressing? Any chance I will be able to include this change in 0.6?

**Comment by linonetwo** [comment]
Since some tests still fail, I can only make a dangerous PR for this.

Failed tests are here:
```javascript
  224 passing (8s)
  5 failing

  1) client should throw an error if response to batch request is not an array:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Timeout.<anonymous> (C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\mocha\lib\runnable.js:232:19)
      at tryOnTimeout (timers.js:232:11)
      at Timer.listOnTimeout (timers.js:202:5)

  2) HTTPBatchedNetworkInterface should correctly return the result for a single request:
     ReferenceError: fetch is not defined
      at HTTPBatchedNetworkInterface.batchedFetchFromRemoteEndpoint (C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:79:16)
      at C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:41:30

  3) HTTPBatchedNetworkInterface should correctly return the results for multiple requests:
     ReferenceError: fetch is not defined
      at HTTPBatchedNetworkInterface.batchedFetchFromRemoteEndpoint (C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:79:16)
      at C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:41:30

  4) HTTPBatchedNetworkInterface middleware should be able to modify requests/options:
     ReferenceError: fetch is not defined
      at HTTPBatchedNetworkInterface.batchedFetchFromRemoteEndpoint (C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:79:16)
      at C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:41:30

  5) HTTPBatchedNetworkInterface opts should be able to modify request headers and method (#920):
     ReferenceError: fetch is not defined
      at HTTPBatchedNetworkInterface.batchedFetchFromRemoteEndpoint (C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:79:16)
      at C:\Users\lindo\Desktop\repo\apollo-test-utils\node_modules\apollo-client\transport\batchedNetworkInterface.js:41:30


```

**Comment by helfer** [comment]
@kamilkisiela can you help @linonetwo ?

**Comment by linonetwo** [comment]
@kamilkisiela Please review it and try run its test https://github.com/apollostack/apollo-test-utils/pull/1

**Comment by kamilkisiela** [comment]
@linonetwo Have you fixed the problems? Do you need my help?

@helfer I was on a vacation for couple of days

**Pull request closed without merging**
