### PR TITLE
Added the fragment flattening

### PR DESCRIPTION
**Pull request by Poincare**
Added fragment definition flattening as per the discussion in #421 and a test for it.
(also, this branch's name is misspelled). 

TODO:

- [ ] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by stubailo** [comment]
What's misspelled?

**Comment by stubailo** [comment]
Seems legit!

**Comment by Poincare** [comment]
The name of the branch on this repo, i.e. "flattening"

**Comment by stubailo** [comment]
I think that's the right spelling! https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=flattening

**Pull request merged**
