### PR TITLE
Drop gql.js into the root and reference to lib so people can npm link without crying

### PR DESCRIPTION
**Pull request by abhiaiyer91**
TODO:

- [ ] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by stubailo** [comment]
Add a comment to the file please? So that people who come along later don't think we're crazy.

**Comment by stubailo** [comment]
Great stuff!

**Comment by abhiaiyer91** [comment]
Ah I didn't add to the change log!!

**Comment by stubailo** [comment]
It's not a user facing change so probably fine!

**Comment by ciwolsey** [comment]
Thanks!  I was struggling with this problem yesterday!

**Pull request merged**
