### PR TITLE
Apollo reducers can't crash the Redux store

### PR DESCRIPTION
**Pull request by rricard**
TODO:
- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

We prevent throwing inside the reducer by wrapping it in a try/catch block. The error will still be reported to the user in the console though.

### CODE REVIEW

**Comment by rricard** [comment]
Intermittent errors seems to appear often in the CI lately

**Comment by helfer** [comment]
@rricard Intermittently failing tests aren't good, I really want to make sure our tests are reliable. Are there any specific tests that you see failing often? Or is it always different ones?

**Comment by helfer** [comment]
@rricard I can't reproduce the intermittent test failures you mention. It works just fine on my machine, actually. Can you tell me which tests cause problems specifically?

**Comment by rricard** [comment]
@helfer I'm taking that back, we indeed need to adapt those tests to my patch. I'll take a look

**Comment by rricard** [comment]
I have some "waiting at the airport" time to kill right now, will work on that!

**Comment by rricard** [comment]
@helfer significantly changed the logic: no "intermittent" bugs now (that was me stupidly defining timeouts as intermittent)

**Comment by rricard** [comment]
Still some residual errors though... easy to fix ...

**Comment by rricard** [comment]
can't get this last error locally ...

**Comment by helfer** [comment]
@rricard I think this would be useful to have in 0.5.0. Any chance you could make a new PR (rebasing is probably too hard)?

**Comment by rricard** [comment]
@helfer was waiting for the refactor to be over to restart fresh. We need this patch in order to be able to use 0.5 so it'll be translated to 0.5!

**Comment by helfer** [comment]
@rricard master is pretty close to what we'll release in 0.5, so if you can update it now, it will be in 0.5. Otherwise I'll release a 0.5.1 with your PR :)

**Comment by rricard** [comment]
@helfer I'll need to figure out the migration path to 0.5 first! So the patch will be for 0.5.1 😉

**Comment by helfer** [comment]
@rricard how's the migration going? I think migrating to 0.5 shouldn't be hard. There were very few breaking changes, and the ones that we had should be easy to fix.

**Comment by rricard** [comment]
@helfer I agree but we didn't have time yet, I'm not even in charge of the migration: however, that's because we started an another project based, this time, on Apollo 0.5, next time I'll have the occasion I'll make a port of this. Sorry for the slowness on my side, we are pretty busy and this is not going to get better until december where I'll have plenty of tie to contrib!

**Comment by rricard** [comment]
Maybe I can try to that this WE... but that's not sure...

**Comment by rricard** [comment]
Closing it in favor of an upcoming PR 🎉

**Comment by rricard** [comment]
here it is: https://github.com/apollostack/apollo-client/pull/874

**Pull request closed without merging**
