### PR TITLE
return result of fetchMore for promise

### PR DESCRIPTION
**Pull request by jbaxleyiii**
TODO:

- [x] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

Need to add a test to ensure this is protected

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@zol @stubailo this should be good to go and allow for test additions to https://github.com/apollostack/react-apollo/pull/120#issuecomment-237780359

**Comment by stubailo** [comment]
Hmm, so for `refetch` we are passing the new query result. Here, it's not completely clear to me - should we pass just the new result from `fetchMore`, or should we pass through the whole merged result from the first query and the new fetch?

What would people use this result for?

**Comment by stubailo** [comment]
Ping!

**Comment by stubailo** [comment]
OK I think we should just pass the new data through, going to merge now.

**Pull request merged**
