### PR TITLE
Explore directives for variable usages in query merging

### LINKED ISSUE #577: [Batching] Query merging seems to discard variables only used in directives
Similarly to #562, when we activate batching with `shouldBatch`, variables only used in directives are not injected correctly in the merged query.

For instance, let's say I'm performing the following query:

```graphql
query SomeQuery($assertion: Boolean!) {
  fieldTrue @include(if: $assertion)
  fieldFalse @skip(if: $assertion)
}
```

it will be rendered in the batch query the following way:

```graphql
query ___composed($___SomeQuery___requestIndex_1___assertion: Boolean!) {
  ___SomeQuery___requestIndex_0___fieldIndex_0: fieldTrue @include(if: $assertion)
  ___SomeQuery___requestIndex_0___fieldIndex_1: fieldFalse @skip(if: $assertion)
}
```

Resulting in the following error:

```
Variable "$assertion" is not defined by operation "___composed".
```

### PR DESCRIPTION
**Pull request by rricard**
Fixes #577

TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)

### CODE REVIEW

**Comment by rricard** [comment]
Size tests are failing, maybe we should add a kB, I think we are on the edge here...

**Comment by stubailo** [comment]
Can you rebase? We added a kB in another patch.

**Comment by rricard** [comment]
done!

**Comment by helfer** [comment]
Cool, thanks a lot!

**Pull request merged**
