### PR TITLE
make afterware errors bubble up

### PR DESCRIPTION
**Pull request by edvinerikson**
This makes errors thrown from afterwares bubble up so that apollo don't try to parse bad responses.

TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by helfer** [comment]
@edvinerikson Thanks for the PR! Can you explain what problem this solves and add a test case if applicable? Right now it doesn't look like your PR would change any behavior.

**Comment by stubailo** [comment]
Looks like the change makes it so that the promise returns the return value of the afterware. However this should definitely come with a test that ensures the behavior continues to work, especially since it's so easy to miss.

**Comment by edvinerikson** [comment]
Yeah I will add a test. I just need to fix my local setup first. Can't run
it locally due to TS errors.

**Comment by edvinerikson** [comment]
@helfer the reason for the change is because I have a afterware which I check the response status and decide if Apollo will be able to parse the response. in some cases Apollo won't be able to do that and when that happens I throw a error which I can catch in my error handling but without this change I am not able to catch the error and instead Apollo will fail with when trying to parse the json body. 

e.g `getDataFromTree(app).catch(error => doSomethingWithErrorHere())` but currently the error I get there will be something like `unexpected token < at 1:1` (due to a html response) instead of my own error.

**Comment by edvinerikson** [comment]
maybe a improvement to the network layer would be to check `response.ok` before trying to parse / handle the response as well. will probably help fix some of the cryptic error messages that I get sometimes.

**Comment by helfer** [comment]
@edvinerikson Okay. Please add a test, and then we can merge it.

I think checking response.ok won't work, because some people return error codes that are not in the 200 range for responses that should be parsed and processed. It's unfortunate, but I think we have to live with that for now.

**Comment by edvinerikson** [comment]
> I think checking response.ok won't work, because some people return error codes that are not in the 200 range for responses that should be parsed and processed. It's unfortunate, but I think we have to live with that for now.

Yeah I will create my own network layer to handle my cases instead.
Still gonna try to add a test and get this merged.

**Comment by edvinerikson** [comment]
test is added

**Comment by helfer** [comment]
Sweet, thanks a lot!

**Pull request merged**
