### PR TITLE
Undo accidental breaking change to updateQueries

### PR DESCRIPTION
**Pull request by stubailo**
TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by drFabio** [comment]
Should updateQueries work as the docs examples now? Mine seems to never be invoked and I am on 0.5.0-1 now

**Comment by drFabio** [comment]
Will make a minimal example first then, it was not working for me but perhaps I am doing something wrong that will show up at minimal example

**Comment by drFabio** [comment]
Ok I may have lost somehting on the way but here it is the client with     "apollo-client": "^0.5.0-1"  and "react-apollo": "^0.5.13",

```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import gql from 'graphql-tag'
import ApolloClient, { createNetworkInterface } from 'apollo-client'
import { ApolloProvider, graphql } from 'react-apollo'
const client = new ApolloClient({
  networkInterface: createNetworkInterface({uri: 'http://localhost:4000/graphql'})
})
const BaseList = React.createClass({
  sendMutation () {
    const data = {name: this.refs.input.value}
    this.props.setMinimal({variables: {data}})
  },
  render () {
    let minimals = []
    if (this.props.data.minimals) {
      minimals = this.props.data.minimals
    }
    return (
      <div>
        <ul>
          {
            minimals.map((item) => {
              return (
                <li key={item.id}>{`${item.id} ${item.name}`}</li>
              )
            })
          }
        </ul>
        <input ref={'input'} />
        <button onClick={this.sendMutation}>
          {'Send'}
        </button>
      </div>
    )
  }
})
const query = gql`
  query{
    minimals{
      id
      name
    }
  }
`
const setMinimalQuery = gql`
  mutation ($data:MinimalInput) {
    setMinimal(data:$data){
      name
      id
    }
  }
`
const updateQueries = {
  'minimals': (previousQueryResult, { mutationResult, queryVariables }) => {
    console.log('it worked somehow')
    console.log(previousQueryResult)
    console.log(mutationResult)
  }
}
const props = ({ ownProps, mutate }) => {
  return {
    setMinimal ({variables}) {
      return mutate({
        variables,
        updateQueries
      })
    }
  }
}
const List = graphql(setMinimalQuery, {props})(graphql(query)(BaseList))
const app = (
  <ApolloProvider client={client} >
    <List />
  </ApolloProvider>
)
ReactDOM.render(
  app,
  document.getElementById('app')
)
```

And here is the dumb server:
```javascript
const express = require('express')
const { apolloExpress, graphiqlExpress  } = require('apollo-server');
const cors = require('cors')
const { makeExecutableSchema } = require('graphql-tools')
const bodyParser = require('body-parser')

const typeDefs = `
  type Minimal{
    id: ID!
    name: String
  }
  input MinimalInput{
     name: String
  }
  type Query {
    minimals:[Minimal]
  }
  type Mutation{
    setMinimal(data:MinimalInput):Minimal
  }
`
let currentId = 3
let theDataBase = [
  {id:1,name:'Foo'},
  {id:2,name:'Bar'}
]
const resolvers = {
  Query: {
    minimals(){
      return theDataBase
    }
  },
  Mutation:{
    setMinimal(root,params){
      const {data} = params
      const newData = {
        id:currentId++,
        name:data.name
      }
      theDataBase.push(newData)
      return newData
    }
  }
}
const schemaOptions = {
  typeDefs,
  resolvers
}
const schema = makeExecutableSchema(schemaOptions)
const app = express()
app.use(cors())

app.use('/graphql',
     bodyParser.json(), 
     apolloExpress({ 
        schema
     })
)
app.use('/graphiql', graphiqlExpress({
  endpointURL: '/graphql',
}));
const httpPort = process.env.PORT || 4000 
app.listen(httpPort,  "0.0.0.0", () => console.log(`Now browse to localhost:${httpPort}/graphiql for UI or localhost:${httpPort}/graphql for API`))

```

**Comment by drFabio** [comment]
The console.log of the updateQueries never get's called

**Comment by stubailo** [comment]
@drFabio I think you're misunderstanding what the "query name" is. This query:

```
 query {
    minimals{
      id
      name
    }
  }
```

Doesn't have a name. It needs to be like this:

```
 query MyQueryName {
    minimals{
      id
      name
    }
  }
```

And then `MyQueryName` is the thing you need to put in `updateQueries`.

**Comment by drFabio** [comment]
Wow thanks @stubailo let that slip past my implementation several times.

**Comment by drFabio** [comment]
What the updateQueries should return? an object with the same shape as prev?

**Pull request merged**
