### PR TITLE
Fixed #713 with OptionalDependencies approach

### LINKED ISSUE #713: Consider moving @types packages from devDependencies to dependencies
The rationale is discussed here:
https://github.com/Microsoft/types-publisher/issues/81

This doesn't prevent my app from running, but the TS errors are pretty annoying especially because they break HMR (with the overlay configured) as shown below:

apollo ts declaration dependencies_censored

### PR DESCRIPTION
**Pull request by poloagustin**
TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by helfer** [comment]
@poloagustin Thanks for the PR! I think we need to have it in both devDependencies and optionalDependencies.

**Comment by poloagustin** [comment]
not a problem 👍

**Comment by stubailo** [comment]
Never mind - let's have it only in `optionalDependencies`, just talked to Jonas

**Comment by antmdvs** [comment]
Perhaps CHANGELOG should be updated to reflect `optionalDependencies` and reference the discussion in #733

**Pull request merged**
