### PR TITLE
fix: afterware network interface aligment

### PR DESCRIPTION
**Pull request by DxCx**
- Bugfix for afterwares (did not wait for promise)
- Change response of afterware to GraphQLResult (more reasonable)
  ** this approach also aligned with the batching network interface **

- [X] Make sure all of the significant new logic is covered by tests
- [X] Rebase your changes on master so that they can be merged easily
- [X] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by helfer** [comment]
Looks good to me, thanks! This is a breaking change, so make sure to add a changelog entry.

**Comment by DxCx** [comment]
Yeah ofcourse, do you know of any doc that needs an update?

**Comment by helfer** [comment]
Yeah, probably this right here: http://dev.apollodata.com/core/network.html#networkInterfaceAfterware

**Comment by DxCx** [comment]
Ok, looks like we are ready,
you can merge this here and then we will progress on docs after your intial review. :)

**Comment by DxCx** [comment]
@helfer can i merge it?

**Comment by helfer** [comment]
I've merged it, but if you want it on a release that comes out before the refactoring is done, we'll have to make the PR against a separate branch that's based off the last released version.

**Comment by DxCx** [comment]
No, not at all, i want it to be released with the refactor, just helping you guys in small stuff i've found and i think can be better. :)

**Comment by stubailo** [comment]
I'm a bit confused about this, since I'm 100% sure people are using afterwares to check the HTTP response code. Wasn't the GraphQL response available before?

**Comment by stubailo** [comment]
I think we should undo this change, and then simply add examples to the docs about how to access the `GraphQLResponse` from the HTTP response. But people also need stuff like headers and HTTP codes.

**Comment by helfer** [comment]
Oh, hm. I was too quick merging this then. Good thing we already have #754

**Comment by helfer** [comment]
Can we write up some better documentation for how to get the parsed response? I remember there was some issue open about it.

**Comment by helfer** [comment]
As discussed with @stubailo over lunch, we could pass the parsed response as another param to the afterware. That would probably solve the problem this PR is trying to solve.

**Comment by DxCx** [comment]
@helfer @stubailo what's im trying to achieve is better define roles between clientInterface logic and implementation.
i tried to push it because i think it should be symmetric,
like the request on middleware is just a graphql request,
then the response should be graphqlish as well.
this especially because network interface should be more generic,
like, for example, if i want to add anohter networkInterface type, i won't necessary will have a protocol layer response with it, it might be pure data. (opening socket for example)

i'll be fine with the suggested solution above, but then i think the networkInterface implementation should also provide a type which state what interface type was used.

**Comment by helfer** [comment]
@DxCx I think that's a good idea in general, but we should discuss the design first. Would you mind writing up a proposal? 
Also, I should mention that I think there are a lot of things to work on in Apollo Client that would be more impactful.

**Comment by DxCx** [comment]
Yeah, i don't mind.

So Generally, my finally goal, is to be able support more then just HTTP for apollo-client,
starting with websocket in the near term and maybe HTTP2 in the future.

So, the main goal here is to separate networkInterface generic/common logic (such as middlewares/batching) from the implementation logic (Http fetch in that case).
to do that, the following steps should be taken:
  1. Make middleware/afterware generic (GraphQL and not networkInterface)
    - That was this patch. which now i want to change to support the following:

      ```typescript
      export interface ResponseAndOptions {
              interfaceType: string;      // string indicating which transport layer is used.
                                                      // afterware might treat response differently depends on that.
              result: GraphQLResult;  // GraphQL parsed response
              response: IResponse;    // GraphQL raw response. (Optional, depends on interfaceType)
              options: RequestInit;
      }
      ```
    NOTE: if the transport layer response is sent to middleware, then middlewares should be able to support errors chain as well. (next(err) should work), else, what/how would you like it to validate?

  2. separate the logics (I have a draft which i still need to work on, but now i got one step back),
      which means:
    - common networkInterface logic will reside in genericNetworkInterface abstract class which will provide an abstract protected/public method to do the network specific operations.
      - for example, HTTPFetchNetworkInterface will inherint the genericNetworkInterface, and then implement just one function which will send the actual fetch.
    - batched interface will become abstract as well and will extend genericNetworkInterface to provide abstracted batching logic.  
    - Another class (HTPPFetchBatchedNetworkInterface) will inherit batchedNetworkInterface and implement the same exact fetch as above.

  3. Convert the inner logic of the generic interfaces to support observables, so observable based network interfaces could be supported. also, observables are compatible with promises, so keeping the external (existing) interfaces as promise is possible. i think that this step alone can be broken as well into a plan and steps but the first 2 steps should be taken first.


from this point, i believe that adding more and more networkInterfaces will be easier as it is much more generic and all that needs to be done to add an interface is to provide 1 function.
also, IMO, this approach will make it easier in the future to release networkInterfaces as different small packages.

**Comment by stubailo** [comment]
Can we open a separate issue for this discussion? I don't think a closed PR is the right place.

**Comment by DxCx** [comment]
You are right @stubailo see #774

**Pull request merged**
