### PR TITLE
add generic types to apollo client for Query and Mutation

### LINKED ISSUE #777: Add generic type to ApolloQueryResult
Idea:

``` ts
ApolloQueryResult<T>
```

``` ts
client.watchQuery<T>(opts).subscribe(result => {
 // result.data: T;
 // result.loading: boolean;
});
```

---

Besides that, imagine GraphQL Documents compiled into TypeScript interfaces combined with this `ApolloQueryResult` that has generic type. We can easily find bugs while writing an app.

### PR DESCRIPTION
**Pull request by brettjurgens**
Fixes #777 

TODO:
- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [x] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by helfer** [comment]
@kamilkisiela do you have a moment to review this PR? I'm asking since you initially had the idea for #777

**Comment by kamilkisiela** [comment]
@helfer I don't get the idea. Why we specify those types while creating an instance of `ApolloClient`?

```ts
ApolloClient<QueryType, MutationType>
```

and

```ts
public watchQuery(...): ObservableQuery<QueryType, MutationType>
```

With this approach, every `watchQuery()` will return an object of the same type, even if each query looks different.

My idea was to specify generic type for each individual `watchQuery`, `query` and `mutate` methods.

**Comment by brettjurgens** [comment]
@kamilkisiela is this more what you're looking for?

**Comment by brettjurgens** [comment]
unfortunately, generics cannot be made optional (there's an issue here: https://github.com/Microsoft/TypeScript/issues/2175), so yes, it will be a breaking change, but quite an easy one to fix (just add `<any>`)

**Comment by kamilkisiela** [comment]
@brettjurgens Yes yes, it's not that I see it as a big problem, it's just a breaking change that will screw up few projects if we will push it as `0.5.X`. With `0.6.0` we can mark it as a Breaking Change to inform people and even with a release candidate, they can be prepared for it.

**Comment by brettjurgens** [comment]
agreed, should not be released in a patch version. `0.6.0` makes sense

**Comment by stubailo** [comment]
This update sure would go well with working TypeScript code gen: https://github.com/apollostack/apollo-codegen/pull/5

**Comment by brettjurgens** [comment]
@stubailo FWIW there's also https://github.com/avantcredit/gql2ts

**Comment by helfer** [comment]
@brettjurgens Sorry I did't get around to doing anything with this PR until now! Do you think you could you change the base of this PR to zero-decimal-six and resolve all the conflicts in the next few days? If so, then we can merge it and release it with version 0.6. Otherwise I think we should probably close the PR and open a new one down the road, because it will only get harder to merge the PR as it gets more out of date with the rest of the code.

**Comment by kamilkisiela** [comment]
@brettjurgens yes, it would be super cool. I could make changes also in `angular2-apollo` in just one release.

**Comment by brettjurgens** [comment]
cool, will rebase on 0.6 right now

**Comment by brettjurgens** [comment]
@helfer just rebased it and the diff between this branch and the `zero-decimal-six` one looks clean

**Comment by brettjurgens** [comment]
@helfer tests are passing now, seems i missed a conflict or two when the base changed. should be all good now

**Comment by helfer** [comment]
@brettjurgens wonderful, thanks for your efforts! It always feels great to merge the oldest PR 😌

**Pull request merged**
