### PR TITLE
fix resetStore running stopped queries

### PR DESCRIPTION
**Pull request by machard**
Hi,

there is an issue actually when stoping a query and then resetting the store.
the query will actually be refetched.

It seems to be a possible logical fix. but it fails tests

### CODE REVIEW

**Comment by machard** [comment]
Ok so i have an other suggestion.
The idea to refresh queries on resetStore is to update the data they hold right ?
So as we just decided to reset the store, ie empty it, why use refresh that forceFetch the query ?
Why not do a noFetch referesh ?

**Comment by machard** [comment]
"Ok, so what about updating ObservableQuery.refetch method to return early if the ObservableQuery has no subscribers ?" it does not work, when the request is resubscribed again, there is an error like that "Store error: the application attempted to write an object with no provided id but the store already contains an id of Viewer15Npslpr16BHoOXFd5lssiqJFBlMNvu6w1c4okJ2OVCX6Pim for this object."

**Comment by machard** [comment]
ok after reading http://dev.apollodata.com/react/auth.html#login-logout, i see that it's intentional to reset the store as it is on the server so none of the 2 methods in the previous comment could be a match.
But it does seem like a real problem that teardowned queries are refetch on reset store.

**Comment by tmeasday** [comment]
I think it is pretty reasonable to not refetch the query if it has been torn down on resetting store. @helfer what do you think?

**Comment by helfer** [comment]
@tmeasday Yes, the query definitely shouldn't be refetched if it has been stopped.

@machard I think the proper fix for now would be to only refetch non-stopped queries [here](https://github.com/apollostack/apollo-client/blob/de8c57fd014c973885526a3190d9ab9d4660b411/src/core/QueryManager.ts#L633).

**Comment by machard** [comment]
is there already a way to know for sure if a request has been toredown (observers.length == 0 ?) or should i add a toredown property to the observableQuery ?

**Comment by machard** [comment]
@helfer ?

**Comment by helfer** [comment]
@machard I'm not sure what you mean. A query isn't started until it has listeners, and when it has no more listeners, it is stopped. What I proposed was checking the `stopped` property in the store before refetching.

**Comment by machard** [comment]
@helfer yes you answered my question. I updated the PR, is that what you expected ?

**Comment by helfer** [comment]
@machard yes, thanks a lot, that's exactly what I meant! It would be awesome if you could add a test for this as well that makes sure stopped queries are really not refetched. Do you think you could do that? Basically it should start a query, then stop it, then call refetch store and make sure no network request is sent. To make sure the test actually works, you could try and see if the test fails when you remove your changes, and passes when you add them back in.

Let me know if you can do it!?

**Comment by machard** [comment]
@helfer done!

**Comment by helfer** [comment]
Thanks a lot, it looks great! 🙂 

I'm going to merge it now, and then make the timeout a bit shorter because nobody wants to wait 400 ms for a test to finish 😉

**Comment by helfer** [comment]
And I guess I'll update the changelog. I didn't even notice that you deleted the todo list that comes with the PR template. That's not what it's for 😄

**Comment by machard** [comment]
cool !
for the timeout, I took the one i saw on other tests :/ https://github.com/apollostack/apollo-client/blob/master/test/QueryManager.ts#L2234 for example

**Comment by helfer** [comment]
@machard Oh, right. I should probably go and reduce those where possible to make tests run faster.

**Pull request merged**
