### PR TITLE
Switch to external graphql-tag package

### LINKED ISSUE #223: Decide on a more elegant solution to make `gql` work with npm link
To fix the current `npm-link` issue, where the module `apollo-client/gql` cannot be found, we will place `gql.js` in the root of the repo and redirect it to `lib/src/`gql.js`.

After a deep discussion about separate modules or not, we decided to go ahead with the current strategy while we think of something better to do. 

This is that issue.

### PR DESCRIPTION
**Pull request by stubailo**
Completes #312.
Fixes #223.

@abhiaiyer91, you might be interested.

This also makes the following unnecessary:

#188 #190 @jbaxleyiii 

TODO:

- [x] Update CHANGELOG.md with your change
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@stubailo do you think it is more efficient (weight wise) to send the parser, or the compiled documents to the client? Mainly for a larger app. I was thinking about writing a meteor build package to take .graphql files to make the importable and parse them but was unsure if it was a good move?

**Comment by stubailo** [comment]
@jbaxleyiii last time I talked to Lee Byron he was thinking it might actually be more efficient to send the parser, depending on how big your queries are. The query AST is potentially large, so just a small number of queries could end up pretty heavy was his thought.

We can also experiment right? I don't think this PR changes anything about that option being available.

**Comment by jbaxleyiii** [comment]
@stubailo I came to the same conclusion. 👍

**Comment by helfer** [comment]
I think the most efficient thing would be to just send the operationName, if that's possible.

**Comment by stubailo** [comment]
@helfer sure, but that's orthogonal to this question because we need to know the query on the client even if we don't send it.

**Pull request merged**
