### PR TITLE
Refactor: remove result behaviors

### PR DESCRIPTION
**Pull request by calebmer**
Removes the result behaviors functionality which provided a declarative configuration for mutations in the style of Relay. This PR was enabled by the `updateQueries` refactor in https://github.com/apollostack/apollo-client/pull/1144 and recommended by @helfer. This PR is therefore blocked by #1144.

For tests I removed all tests that addressed `resultBehaviors` functionality and refactored tests that merely used `resultBehaviors` to test something else to keep coverage high. I may have accidentally deleted some tests though so keep that in mind when you review.

We need to discuss whether we want to land this now (it is undocumented so the argument may be made that it is not a breaking change) or wait until 1.0. In my opinion if 1.0 will be released in 1–2 weeks (which is highly unlikely) we should wait to release this with 1.0. Otherwise we should release it as soon as possible to avoid the branch getting out of sync with `master`.

I think it is safe to assume that even though this is undocumented at least one person found and now uses this feature. As that tends to be how open source software works.

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change

### CODE REVIEW

**Comment by calebmer** [comment]
Since this PR currently includes #1144 as it has not yet been merged here is a diff between #1144 and this PR: https://github.com/apollostack/apollo-client/compare/fix/dependent-optimistic-updates...refactor/remove-result-behaviors

**Comment by stubailo** [comment]
The result behavior stuff includes some useful utilities for doing stuff with the store, for example removing all occurrences of a specific id.

Would it be worth factoring those into a new library so that people can still do similar behaviors in custom reducers? That would also make the migration a lot easier for people who are using these features.

**Comment by calebmer** [comment]
Which ones might be useful to keep? `cleanArray` maybe? It looks like nothing was being exported out of Apollo Client except the `MutationBehavior` type that got deleted.

> Would it be worth factoring those into a new library so that people can still do similar behaviors in custom reducers? That would also make the migration a lot easier for people who are using these features.

Oh, I see what you mean :blush:

I think if people were using these features and want to keep using them we can guide them to creating a separate library using the code we had, but I’m not sure if it’s something worth doing proactively.

**Comment by stubailo** [comment]
Fair enough - I think one blocker is that the code for writing to the store is not really exported anywhere.

**Comment by benwiley4000** [comment]
A bit bummed about this - I was trying to find docs then realized the feature was removed. @calebmer @stubailo what is the recommended method for declaratively updating collections after mutations in apollo ^1.0? Needing to imperatively mutate collections client-side after any mutation seems very un-declarative/GraphQL, and `refetchQueries` isn't really the best solution (it's good to do, but it's not the same thing).

**Comment by stubailo** [comment]
This is our replacement API: https://dev-blog.apollodata.com/apollo-clients-new-imperative-store-api-6cb69318a1e3

Our current position is that "declarative" approaches to post-mutation updates actually end up with really contrived code, and all GraphQL clients including Relay are moving away from that approach. Are you missing anything from the new API? What are some use cases you are trying to handle?

**Comment by benwiley4000** [comment]
@stubailo Thank you for the response! And I see. I do see where you're coming from.

I have a hard time wrapping my head around the need to explicitly re-tell my Apollo store what the result of a particular query is, in order to update my normalized data state. The initial query is declared to the server with GraphQL, then all the additional updates are imperatively assigned on the client without it? Weird!!

I understand that with the mutation/querying logic being obfuscated from the client on the server, it will be hard to automatically infer changes to query results.

What I want, I guess, and maybe this is a GraphQL problem, is a way for the relationship between queries and mutations to be obvious to the client. That might require a new mutation syntax.

Maybe instead of:

```graphql
mutation ($text: String!) {
  createTodo(text: $text) {
    id
    text
    completed
  }
}
```

We would have something like:

```graphql
mutation ($text: String!) {
  todos:add {
    text: $text
    completed: false
  }
}
```

or to delete:

```graphql
mutation ($id: Int!) {
  todos:delete {
    id: $id
  }
}
```

That's kind of rough I guess, and servers would still be responsible for real implementation details, but a graphql client could be able to infer changes this way.

**Comment by stubailo** [comment]
Yeah, in the short term we aren't considering any solutions that require changes to GraphQL syntax.

**Comment by benwiley4000** [comment]
Right - I understand this, and again I see how imperative client updates are an OK solution to what is possible now, but I think they're symptomatic of a flaw in GraphQL's design.

**Pull request merged**
